### ISSUE TITLE
EoS for authentication returned as 000000000000000

### ISSUE THREAD

**Issue by xsicho** [gogcom/galaxy-ue4-oss-plugin#3]
Hello! My team is currently working on Authentication of Epic Online Service with Unreal C++ and we've encountered a problem. We are unable to fully comprehend how to use the RequestEncrypedAppTicket() and IUser::GetEncryptedAppTicket() in the GoG SDK which we have tried writing the codes as follow and received invalid and unusable values. Can you please help us with a sample code or tell us how to properly output the values of these functions?

AppTicketListener* SObj = new AppTicketListener();
galaxy::api::User()->RequestEncryptedAppTicket(NULL, 0,(galaxy::api::IEncryptedAppTicketListener*) SObj);

class AppTicketListener : galaxy::api::IEncryptedAppTicketListener  {
public:
        void OnEncryptedAppTicketRetrieveSuccess() {

            uint8 data[4096]="";
            uint32 ExactTicketSize = 0;
            galaxy::api::User()->GetEncryptedAppTicket(data, 0, ExactTicketSize);
            char TokenBuffer[4096];
            uint32_t TokenLen = 4096;
            auto Res = EOS_ByteArray_ToString(data, ExactTicketSize, TokenBuffer, &TokenLen); //unreal macro to convert byte to char

            Tokens = FString(ANSI_TO_TCHAR(TokenBuffer)); // a token for Epic online service for Authentication  เราได้ 000000000000000  ซึ่ง มัน Invalid

        }
        void OnEncryptedAppTicketRetrieveFailure(galaxy::api::IEncryptedAppTicketListener::FailureReason failureReason) {
        //do something on fail
        }
}

**Comment by Vegebutcher** [comment]
Please refer to [Authorizing GOG GALAXY Users in Third-Party Services](https://docs.gog.com/sdk-encrypted-tickets/) article in the dev docs. If your problem persists, please [submit a ticket](https://galaxy-support.gog.com/hc/en-us/requests/new) to the GOG support.

**Comment by petracles** [comment]
Hey @xsicho - I ran into the same issue and was wondering if you found a solution or submitted a ticket that I can follow along with. Any info/help appreciate, thanks!
